/*
 * File: app/store/Canon.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PnZ.store.Canon', {
    extend: 'Ext.data.Store',

    requires: [
        'PnZ.model.CameraDetails'
    ],

    config: {
        data: [
            {
                name: 'Canon EOS 1DX'
            },
            {
                name: 'Canon EOS 6D'
            },
            {
                name: 'Canon EOS 7D'
            },
            {
                name: 'Canon EOS 70D'
            },
            {
                name: 'Canon EOS 5D Mark |'
            },
            {
                name: 'Canon EOS 5D Mark ||'
            },
            {
                name: 'Canon 7D Mark ||'
            },
            {
                name: 'Canon EOS 600D'
            },
            {
                name: 'Canon 50mm/E1.2c'
            },
            {
                name: 'Canon 65mm/E1.1x'
            },
            {
                name: 'Canon 70mm/E1.7c'
            },
            {
                name: 'Canon 85mm/E1.9c'
            },
            {
                name: 'Canon 115mm/E2.3c'
            }
        ],
        model: 'PnZ.model.CameraDetails',
        storeId: 'Canon'
    }
});