/*
 * File: app/store/Nikon.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PnZ.store.Nikon', {
    extend: 'Ext.data.Store',

    requires: [
        'PnZ.model.CameraDetails'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        data: [
            {
                name: 'Nikon D800E'
            },
            {
                name: 'Nikon D610'
            },
            {
                name: 'Nikon D7100'
            },
            {
                name: 'Nikon D7000'
            },
            {
                name: 'Nikon D3300'
            },
            {
                name: 'Nikon D810'
            },
            {
                name: 'Nikon D5200'
            },
            {
                name: 'Nikon 35mm / F1.8'
            },
            {
                name: 'Nikon 50mm / F1.8'
            },
            {
                name: 'Nikon 85mm / F1.8'
            },
            {
                name: 'Nikon 105mm / F1.8'
            },
            {
                name: 'Nikon 135mm / F1.8'
            }
        ],
        model: 'PnZ.model.CameraDetails',
        storeId: 'Nikon'
    }
});