/*
 * File: app/view/HomeScreen.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PnZ.view.CartScreen', {
    extend: 'Ext.Container',
    alias: 'widget.cartscreen',

    requires: [
        'Ext.Toolbar',
        'Ext.Label',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        scrollable: null,
        items: [
            {
                xtype: 'tabpanel',
                itemId: 'tabPanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Nikon',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'nikonList',
                                itemTpl: [
                                    '<div class=\'camera-details\'>{name}<input type="checkbox" style=\'float: right; margin-right: 10px;\' name=\'\'></div>'
                                ],
                                store: 'Nikon'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Canon',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'cannonList',
                                itemTpl: [
                                    '<div class=\'camera-details\'>{name}<input type="checkbox" style=\'float: right; margin-right: 10px;\' name=\'\'></div>'
                                ],
                                store: 'Canon'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Acc.',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'accList',
                                itemTpl: [
                                    '<div class=\'camera-details\'>{name}<input type="checkbox" style=\'float: right; margin-right: 10px;\' name=\'\'></div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Lighting',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'lightList',
                                itemTpl: [
                                    '<div class=\'camera-details\'>{name}<input type="checkbox" style=\'float: right; margin-right: 10px;\' name=\'\'></div>'
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
        this.relayEvents(this,['painted']);
    }

});